name: Pre-commit Checks

on: [push, pull_request]

jobs:
  format-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.9"

      - name: Install pre-commit
        run: |
          python -m pip install --upgrade pip
          pip install pre-commit==4.2.0

      - name: Clean pre-commit cache
        run: pre-commit clean

      - name: Debug isort version
        run: |
          pre-commit run isort --all-files --verbose

      - name: Run pre-commit on all files
        run: pre-commit run --all-files --show-diff-on-failure